//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doctores.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.HospitalSoap")]
    public interface HospitalSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ver_Todo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Ver_Todo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ver_Todo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Ver_TodoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insertar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Insertar(string DIRECCION, string NOMBRE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insertar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsertarAsync(string DIRECCION, string NOMBRE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Actualizar(string DIRECCION, string NOMBRE, int ID_HOSPITAL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ActualizarAsync(string DIRECCION, string NOMBRE, int ID_HOSPITAL);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HospitalSoapChannel : Doctores.ServiceReference1.HospitalSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HospitalSoapClient : System.ServiceModel.ClientBase<Doctores.ServiceReference1.HospitalSoap>, Doctores.ServiceReference1.HospitalSoap {
        
        public HospitalSoapClient() {
        }
        
        public HospitalSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HospitalSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HospitalSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HospitalSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Ver_Todo() {
            return base.Channel.Ver_Todo();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Ver_TodoAsync() {
            return base.Channel.Ver_TodoAsync();
        }
        
        public string Insertar(string DIRECCION, string NOMBRE) {
            return base.Channel.Insertar(DIRECCION, NOMBRE);
        }
        
        public System.Threading.Tasks.Task<string> InsertarAsync(string DIRECCION, string NOMBRE) {
            return base.Channel.InsertarAsync(DIRECCION, NOMBRE);
        }
        
        public string Actualizar(string DIRECCION, string NOMBRE, int ID_HOSPITAL) {
            return base.Channel.Actualizar(DIRECCION, NOMBRE, ID_HOSPITAL);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarAsync(string DIRECCION, string NOMBRE, int ID_HOSPITAL) {
            return base.Channel.ActualizarAsync(DIRECCION, NOMBRE, ID_HOSPITAL);
        }
    }
}
